# Generated by Django 2.0.1 on 2018-12-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя крошки')),
                ('birthday', models.DateField(verbose_name='дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(verbose_name='описание фотографии')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Child')),
            ],
        ),
    ]
