# Generated by Django 2.0.1 on 2018-12-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(height_field=50, upload_to='child/photo', width_field=50),
        ),
    ]
