# Generated by Django 2.1.4 on 2018-12-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_auto_20181213_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание фотографии'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='child/photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='название фотографии'),
        ),
    ]
