# Generated by Django 2.1.4 on 2018-12-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20181219_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Мальчик'), (2, 'Девочка')], null=True, verbose_name='Пол'),
        ),
    ]
