# Generated by Django 2.1.4 on 2018-12-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_child_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Родственник', max_length=100, verbose_name='Имя родственника')),
                ('relationship', models.CharField(max_length=100, verbose_name='Отношение')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Child')),
            ],
        ),
    ]
