# Generated by Django 2.1.4 on 2018-12-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0007_familymember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamilyMember',
            new_name='Family',
        ),
    ]
