# Generated by Django 2.1.4 on 2018-12-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_auto_20181221_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family',
            new_name='FamilyMember',
        ),
    ]
