# Generated by Django 2.1.4 on 2019-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0010_familymember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(verbose_name='дата'),
        ),
    ]
